random_seed: 0b011011
run_name: "EXP3_RVQ"
# extend

#-----------------------------------------------
#1. Dataset
#-----------------------------------------------

dataset:
  ratio: 0.9
  wb_train: [
              "/home/woongjib/Projects/Dataset/FSD50K_WB_SEGMENT/",  
              "/home/woongjib/Projects/Dataset/MUSDB_WB_SEGMENT/", 
              # "/home/woongjib/Projects/Dataset/VCTK_WB_SEGMENT_"
              ]
  nb_train: [
              "/home/woongjib/Projects/Dataset/FSD50K_LPF/",  
              "/home/woongjib/Projects/Dataset/MUSDB_LPF/", 
              # "/home/woongjib/Projects/Dataset/VCTK_HEAAC_LPF"
              ]
  enhance: False
  # dataset = CustomDataset(["/home/woongjib/Projects/Dataset/FSD50K_WB_SEGMENT", "/home/woongjib/Projects/Dataset/MUSDB_WB_SEGMENT"], 
  #                         ["/home/woongjib/Projects/Dataset/FSD50K_WB_SEGMENT", "/home/woongjib/Projects/Dataset/MUSDB_WB_SEGMENT"], 0.9, enhance=False)
                          
  
  wb_test: [
              "/home/woongjib/Projects/USAC44_mono_48k", 
              ]
  nb_test: [
              "/home/woongjib/Projects/USAC44_mono_48k_HEAAC16_LPF_Crop", 
              ]

#So for this case, wideband test dataset should be located at "/media/zeroone/target/test"

  batch_size: 16
  seg_len: 0.9

  ## Segment audio length
  num_workers: 8
 
#-----------------------------------------------
#2. Model
#-----------------------------------------------

model:
  generator: SEANet_TFiLM_RVQ
  # hubert, w2v, wavlm
  ms_mel_loss_config:
            n_fft_list: [32, 64, 128, 256, 512, 1024, 2048]
            hop_ratio: 0.25
            mel_bin_list: [5, 10, 20, 40, 80, 160, 320]
            reduction: mean
            loss_ratio: 1.0
            sr: 48000
            fmin: 0
  kmeans_path: None
  in_channels: 32
  fe_weight_path: None
  min_dim: 16
  train_enc: True

  discriminator: MBSTFTD
  MultiBandSTFTDiscriminator_config:
      C: 32
      n_fft_list: [2048, 1024, 512]
      hop_len_list: [512, 256, 128]
      band_split_ratio:
          - [0.0, 0.1] # check only 4.5 kHz above
          - [0.1, 0.25] # 0.1 -> 0.1875
          - [0.25, 0.5]
          - [0.5, 0.75]
          - [0.75, 1.0]

#-----------------------------------------------
#3. Loss
#-----------------------------------------------
loss:
  lambda_mel_loss: 1
  lambda_fm_loss: 100
  lambda_adv_loss: 1
  lambda_commitment_loss: 0.25 # only for RVQ models
  lambda_codebook_loss: 1

#-----------------------------------------------
#4. Optimizer (ADAM)
#-----------------------------------------------

optim:
  learning_rate: 0.0001
  scheduler_gamma: 1
  B1: 0.5
  B2: 0.9


#-----------------------------------------------
#Training
#-----------------------------------------------
train:
  # epoch_save_start: 1
  val_epoch: 1
  
  ckpt_save_dir: "./ckpts/EXP3"
  max_epochs: 50

  devices:
    - 0
    #- 1
    # -2 ... if you are using DDP

  # True if load from previous
  ckpt: False
  ckpt_path: ""